### ISSUE TITLE
local integration testing environment useful?

### ISSUE THREAD

**Issue by jspaaks** [jspaaks/getting-started-with-xenon#13]
is it possible and useful to set up a local integration testing environment with Docker?

**Comment by sverhoeven** [comment]
Yes it is possibe see https://github.com/NLeSC/Xenon/blob/fixingTestsAndTime/src/integrationTest/docker/README.md 

It is useful for Xenon developers so they can test changes before pushing.

**Comment by jspaaks** [comment]
migrated
